/**
 * \file mbedtls/config_psa_from_mbedtls.h
 * \brief Construct a PSA crypto configuration (PSA_WANT_xxx) from the
 *        legacy Mbed TLS crypto configuration (MBEDTLS_xxx).
 *
 * Do not include this header directly! It is automatically included
 * by public headers as needed.
 *
 * This file is used when #MBEDTLS_PSA_CRYPTO_C is enabled and
 * #MBEDTLS_PSA_CRYPTO_CONFIG disabled. It creates a PSA configuration
 * with similar functionality as the legacy crypto configuration.
 *
 * Do not edit this file to configure Mbed TLS. Instead, please edit
 * include/mbedtls/mbedtls_config.h for MBEDTLS_XXX settings or
 * include/psa/crypto_config.h for PSA_WANT_XXX settings.
 *
 * This file enables a cryptographic mechanism through the PSA API
 * (by defining PSA_WANT_xxx symbols)
 * when the corresponding mechanism is enabled through the legacy API
 * (by defining MBEDTLS_xxx symbols in include/mbedtls/mbedtls_config.h
 * or a user-defined configuration file).
 */

/*
 *  Copyright The Mbed TLS Contributors
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); you may
 *  not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

#ifndef MBEDTLS_CONFIG_PSA_FROM_MBEDTLS_H
#define MBEDTLS_CONFIG_PSA_FROM_MBEDTLS_H

#if defined(MBEDTLS_PSA_CRYPTO_CONFIG)
#error "File included in the wrong context"
#endif

#endif /* MBEDTLS_CONFIG_PSA_FROM_MBEDTLS_H */
