
/*
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
 */

/*
 * milagro.h
 * 
 * support for milagro_p2p and milagro_cs
 * require an extern library: milagro-crypto
 *
 */



#ifndef milagro_h
#define milagro_h

#include "mpin.h"
#include "utils.h"
#include "wcc.h"
#include "mbedtls/entropy.h"

#define mbedtls_calloc    calloc
#define mbedtls_free       free

#define MBEDTLS_SIZE_PMASTER_MILAGRO_CS      PAS /* 128 bits */
#define MBEDTLS_SIZE_PMASTER_MILAGRO_P2P     PAS /* 128 bits */
#define MILAGRO_CS_TV_DIFFERENCE             5   /* maximum difference of time_values permitted */
#define hashDoneOFF                          0   /* parameter needed by Milagro_p2p */
#define hashDoneON                           1   /* parameter needed by Milagro_p2p */



/* defined below */
typedef struct mbedtls_milagro_cs_context mbedtls_milagro_cs_context;
typedef struct mbedtls_milagro_p2p_context mbedtls_milagro_p2p_context;



/**
 * \brief           Allocating function used internally in milagro.c
 *
 * \param nbytes    number of bytes to allocate
 */
void* mbedtls_alloc_or_die(size_t nbytes);

/**
 * \brief                Freeing function used internally in milagro.c
 *
 * \param to_be_freed    octet to be freed
 */
void mbedtls_free_octet(octet *to_be_freed);

// Milagro Client-to-Server

/**
 * \brief           Struct inside handshake for MILAGRO_CS
 *
 * \note            the octet struct is defined in the
 *                  milagro-crypto library
 */
struct mbedtls_milagro_cs_context
{
    /*
     * See the paper M-Pin: A Multi-Factor Zero Knowledge Authentication
     * Protocol by Michael Scott for the notation
     */
#if defined(MBEDTLS_SSL_CLI_C)
    octet X;                  /*!< Random number internally generated by the client                   */
    octet G1;                 /*!< Parameter for the computation of the key                           */
    octet G2;                 /*!< Parameter for the computation of the key                           */
    octet time_permits;       /*!< Time Permits in case is required, otherwise is NULL                */
    int pin;                  /*!< 4 digit pin, is 0 if not required                                  */
#endif
#if defined(MBEDTLS_SSL_SRV_C)
    octet HID;                 /*!< Parameter owned only by the server (case no time permits)          */
    octet HTID;                /*!< Parameter owned only by the server (case with time permits)        */
#endif
    octet param_rand;         /*!< Random number internally generated by the server and client        */
    octet W;                  /*!< Public parameter sent to the client for the key computation        */
    octet R;                  /*!< Public parameter sent to the server for the key computation        */
    octet secret;             /*!< Secret provided by the TA (different for client and server)
                                    in case of required PIN, is the token                             */
    octet U;                  /*!< It is the output x.H(ID), in case of time permit has
                                    to be set to NULL                                                 */
    octet UT;                 /*!< It is the output x.(H(ID)+H(d|H(ID))) in case of Time Permit       */
    octet client_identity;    /*!< Client's identity                                                  */
    octet hash_client_id;     /*!< Hash of the client's identity                                      */
    octet Y;                  /*!< Parameter computed from both sides                                 */
    octet V;                  /*!< Output point on EC computed by the client for the authentication    */
    octet H;                  /*!< Hash of some parameters computed at both sides                     */
    octet Key;                /*!< Key generated at the end of the MILAGRO_CS protocol                */
    csprng RNG;               /*!< Random Number Generator                                            */
    int date;                 /*!< date to use in case of Time Permits, otherwise is set to 0         */
    unsign32 timevalue;            /*!< time value to use in case of Time Permits, otherwise is set to 0   */
};


/**
 * \brief           Initialize an milagro_cs struct
 *
 * \param milagro_cs          milagro_cs to be initialized
 *
 */
void mbedtls_ssl_milagro_cs_init( struct mbedtls_milagro_cs_context * milagro_cs);


/**
 * \brief           Set up the random number generator for the milagro_cs struct
 *
 * \note            the seed came from this library, the random generator
 *                  from the milagro-crypto library
 *
 * \param milagro_cs      milagro_cs struct which contains the parameter RNG to be
 *                  set up
 * \param entropy       entropy already initialized
 *
 */
int mbedtls_ssl_milagro_cs_setup_RNG( mbedtls_milagro_cs_context *milagro_cs, mbedtls_entropy_context *entropy);


/**
 * \brief           Set up the secret provided by the DTAs
 *
 * \param milagro_cs      milagro_cs struct which contains the parameters
 *                        to be initialized
 * \param secret          secret to store
 * \param len_secret      length of the secret
 *
 */
void mbedtls_ssl_milagro_cs_set_secret( mbedtls_milagro_cs_context *milagro_cs, char* secret, int len_secret);

#if defined(MBEDTLS_SSL_CLI_C)
/**
 * \brief           Set up the secret provided by the DTAs
 *
 * \param milagro_cs      milagro_cs struct which contains the parameters
 *                        to be initialized
 * \param client_identity       the identity of the client
 *
 */
void mbedtls_ssl_milagro_cs_set_client_identity(mbedtls_milagro_cs_context *milagro_cs, char * client_identity);
#endif

/**
 * \brief           Set up the parameters used by the milagro_cs
 *
 * \param milagro_cs      milagro_cs struct which contains the parameters
 *                        to be initialized
 * \param timepermit          time permit for the client
 * \param len_timepermit      length of time permit
 *
 */
void mbedtls_ssl_milagro_cs_set_timepermit( mbedtls_milagro_cs_context *milagro_cs, char* timepermit, int len_timepermit);


/**
 * \brief          Alloc memory for the parameters used by the milagro_cs, inc
 *                 case of the client it computes also the public parameters to
 *                 be sent with the clientHello
 *
 * \param client_or_server 1 if server, 0 if client
 * \param milagro_cs      milagro_cs struct which contains the parameters
 *                  to be initialized
 *
 */
int mbedtls_ssl_milagro_cs_alloc_memory(int client_or_server, mbedtls_milagro_cs_context *milagro_cs);

/**
 * \brief           Check if the server's parameters are ok
 *
 *
 * \param client_or_server      0 if client, 1 if server
 * \param milagro_cs      milagro_cs struct which contains the parameters
 *                  to be initialized
 *
 * \retun           0 if the parameters are good, -1 otherwise
 *
 */
int mbedtls_milagro_cs_check(int client_or_server, mbedtls_milagro_cs_context *milagro_cs );

#if defined(MBEDTLS_SSL_SRV_C)
/**
 * \brief           read the parameters sent by the client
 *
 *
 * \param milagro_cs      milagro_cs struct in which the parameters has to be
 *                        stored
 * \param buf             buffer where to copy the parameters
 * \param len             length of the extension
 *
 */
int mbedtls_milagro_cs_read_client_parameters( mbedtls_milagro_cs_context *milagro_cs, const unsigned char *buf, size_t len );

/**
 * \brief           read the parameters sent by the client
 *
 *
 * \param milagro_cs      milagro_cs struct in which the parameters has to be
 *                  stored
 *
 * \retun           0 if the reading finish well, -1 otherwise
 *
 */
int mbedtls_milagro_cs_authenticate_client( mbedtls_milagro_cs_context *milagro_cs );

#endif

/**
 * \brief           Generate and write the public parameter in order to
 *                  compute the key (TLS: contents of the Client/ServerKeyExchange)
 *
 * \param client_or_server      0 if client, 1 if server
 * \param milagro_cs            Context to use
 * \param buf                   Buffer to write the contents to
 * \param len                   Buffer size
 * \param ec_point_len          Will be updated with the number of bytes written
 *
 * \return                      0 if successful, a negative error code otherwise
 *
 */
int mbedtls_milagro_cs_write_exchange_parameter( int client_or_server, mbedtls_milagro_cs_context *milagro_cs,
                                          unsigned char *buf, size_t len, size_t *ec_point_len );


/**
 * \brief           Read the public parameter for the computation of the Key
 *                  (TLS: contents of the Client/ServerKeyExchange)
 *
 * \param client_or_server      0 if client, 1 if server
 * \param milagro_cs            Context to use
 * \param buf                   Pointer to the message
 * \param len                   Message length
 *
 * \return                      0 if successful, a negative error code otherwise
 *
 */
int mbedtls_milagro_cs_read_public_parameter( int client_or_server, mbedtls_milagro_cs_context *milagro_cs,
                                       const unsigned char *buf, size_t len  );

/**
 * \brief           Free the context milagro_cs
 *
 * \param milagro_cs      milagro_cs context to be freed
 *
 */
void mbedtls_milagro_cs_free( mbedtls_milagro_cs_context *milagro_cs);



// Milagro Peer-to-Peer

// peer1 is the server
// peer2 is the client


/**
 * \brief           struct inside the handshake for MILAGRO_P2P
 *
 * \note            the octet struct is defined in the
 *                  milagro-crypto library
 */
struct mbedtls_milagro_p2p_context
{
    /*
     * See the paper TODO what paper?
     *
     */
    int date;                  /*!< set to zero in case of not using time permit                      */
    octet client_rec_key;      /*!< Client's receiver key provided by the TA                          */
    octet server_sen_key;      /*!< Server's sender key provided by the TA                            */
    octet X;                   /*!< Random number internally generated by the server                  */
    octet W;                   /*!< Random number internally generated by the client                  */
    octet Y;                   /*!< Random number internally generated by the client                  */
    octet server_identity;     /*!< Client Identity                                                   */
    octet client_identity;     /*!< Server Identity                                                   */
    octet server_pub_param_G1; /*!< Server's public parameter in the group G1                         */
    octet client_pub_param_G1; /*!< Client's public parameter in the group G1                         */
    octet client_pub_param_G2; /*!< Client's public parameter in the group G2                         */
    octet client_PIA;          /*!< Client's private parameter                                        */
    octet client_PIB;          /*!< Client's private parameter                                        */
    octet shared_secret;       /*!< Shared secret computed by at the two sides                        */
    csprng RNG;                /*!< Random Number Generator                                           */
};



/**
 * \brief                  Initialize an milagro_p2p struct
 *
 * \param milagro_p2p      milagro_cs to be initialized
 *
 */
void mbedtls_ssl_milagro_p2p_init( mbedtls_milagro_p2p_context * milagro_p2p);


/**
 * \brief                 Set up the receiver/sender key provided by the DTAs
 *
 * \param milagro_p2p     milagro_p2p struct which contains the parameters
 *                        to be initialized
 * \param key             sender/receiver key to store
 * \param len_key         length of the key
 *
 */
void mbedtls_ssl_milagro_p2p_set_key(int client_or_server, mbedtls_milagro_p2p_context *milagro_p2p, char* key, int len_key);


/**
 * \brief                 Make the first server's side computation
 *
 * \param milagro_p2p     milagro_p2p struct which contains the parameters
 *
 * \return                0 if successful, error otherwise
 */
int mbedtls_milagro_p2p_compute_public_param( mbedtls_milagro_p2p_context *milagro_p2p);


/**
 * \brief                Set up the random number generator for the milagro_p2p struct
 *
 * \note                 the seed came from this library, the random generator
 *                       from the milagro-crypto library
 *
 * \param milagro_p2p    milagro_cs struct which contains the parameter RNG to be
 *                       set up
 * \param entropy        entropy already initialized
 *
 */
int mbedtls_ssl_milagro_p2p_setup_RNG( mbedtls_milagro_p2p_context *milagro_p2p, mbedtls_entropy_context *entropy);


/**
 * \brief                     Allocate memory and store the identity
 *
 * \param client_or_server    1 if server, 0 if client
 * \param milagro_p2p         milagro_p2p struct which contains the parameter
 * \param identity            identity to be stored
 *
 * \return                    0 if successful, error otherwise
 */
int mbedtls_ssl_milagro_p2p_set_identity(int client_or_server, mbedtls_milagro_p2p_context *milagro_p2p, char * identity);


/**
 * \brief                     Alloc memory for the struct milagro_p2p
 *
 * \param client_or_server    1 if server, 0 if client
 * \param milagro_p2p         milagro_p2p struct which contains the parameters
 *                            to be initialized
 *
 * \return                    0 if successful, error otherwise
 */int mbedtls_ssl_milagro_p2p_alloc_memory(int client_or_server, mbedtls_milagro_p2p_context *milagro_p2p);


/**
 * \brief                       Generate and write the public parameter (ServerKeyExchange)
 *
 * \param client_or_server      0 if client, 1 if server
 * \param milagro_p2p           Context to use
 * \param buf                   Buffer to write the contents to
 * \param len                   Buffer size
 * \param param_len             Will be updated with the number of bytes written
 *
 * \return                      0 if successful,
 *                              a negative error code otherwise
 */
int mbedtls_milagro_p2p_write_public_parameters(int client_or_server, mbedtls_milagro_p2p_context *milagro_p2p,
                                                unsigned char *buf, size_t len, size_t *param_len );


/**
 * \brief                       Read the public parameter (KeyExchange)
 *
 * \param client_or_server      0 if client, 1 if server
 * \param milagro_p2p           Context to use
 * \param buf                   Pointer to the message
 * \param len                   Message length
 *
 * \return                      0 if successful,
 *                              a negative error code otherwise
 */
int mbedtls_milagro_p2p_read_public_parameters( int client_or_server, mbedtls_milagro_p2p_context *milagro_p2p,
                                             const unsigned char *buf, size_t len  );


/**
 * \brief           Free the context milagro_p2p
 *
 * \param milagro_p2p      milagro_p2p context to be freed
 *
 */
void mbedtls_milagro_p2p_free( mbedtls_milagro_p2p_context *milagro_p2p);


#endif /* milagro_h */






