# CMake generated Testfile for 
# Source directory: /home/jordan/mbedtls/tests
# Build directory: /home/jordan/mbedtls/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(aes.ecb-suite "test_suite_aes.ecb")
set_tests_properties(aes.ecb-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;47;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(aes.cbc-suite "test_suite_aes.cbc")
set_tests_properties(aes.cbc-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;48;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(aes.cfb-suite "test_suite_aes.cfb")
set_tests_properties(aes.cfb-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;49;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(aes.rest-suite "test_suite_aes.rest")
set_tests_properties(aes.rest-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;50;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(arc4-suite "test_suite_arc4")
set_tests_properties(arc4-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;51;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(asn1write-suite "test_suite_asn1write")
set_tests_properties(asn1write-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;52;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(base64-suite "test_suite_base64")
set_tests_properties(base64-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;53;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(blowfish-suite "test_suite_blowfish")
set_tests_properties(blowfish-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;54;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(camellia-suite "test_suite_camellia")
set_tests_properties(camellia-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;55;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(ccm-suite "test_suite_ccm")
set_tests_properties(ccm-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;56;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(cipher.aes-suite "test_suite_cipher.aes")
set_tests_properties(cipher.aes-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;57;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(cipher.arc4-suite "test_suite_cipher.arc4")
set_tests_properties(cipher.arc4-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;58;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(cipher.blowfish-suite "test_suite_cipher.blowfish")
set_tests_properties(cipher.blowfish-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;59;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(cipher.camellia-suite "test_suite_cipher.camellia")
set_tests_properties(cipher.camellia-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;60;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(cipher.ccm-suite "test_suite_cipher.ccm")
set_tests_properties(cipher.ccm-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;61;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(cipher.des-suite "test_suite_cipher.des")
set_tests_properties(cipher.des-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;62;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(cipher.gcm-suite "test_suite_cipher.gcm")
set_tests_properties(cipher.gcm-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;63;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(cipher.null-suite "test_suite_cipher.null")
set_tests_properties(cipher.null-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;64;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(cipher.padding-suite "test_suite_cipher.padding")
set_tests_properties(cipher.padding-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;65;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(cmac-suite "test_suite_cmac")
set_tests_properties(cmac-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;66;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(ctr_drbg-suite "test_suite_ctr_drbg")
set_tests_properties(ctr_drbg-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;67;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(debug-suite "test_suite_debug")
set_tests_properties(debug-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;68;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(des-suite "test_suite_des")
set_tests_properties(des-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;69;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(dhm-suite "test_suite_dhm")
set_tests_properties(dhm-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;70;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(ecdh-suite "test_suite_ecdh")
set_tests_properties(ecdh-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;71;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(ecdsa-suite "test_suite_ecdsa")
set_tests_properties(ecdsa-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;72;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(ecjpake-suite "test_suite_ecjpake")
set_tests_properties(ecjpake-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;73;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(ecp-suite "test_suite_ecp")
set_tests_properties(ecp-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;74;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(entropy-suite "test_suite_entropy")
set_tests_properties(entropy-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;75;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(error-suite "test_suite_error")
set_tests_properties(error-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;76;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(gcm.aes128_en-suite "test_suite_gcm.aes128_en")
set_tests_properties(gcm.aes128_en-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;77;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(gcm.aes192_en-suite "test_suite_gcm.aes192_en")
set_tests_properties(gcm.aes192_en-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;78;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(gcm.aes256_en-suite "test_suite_gcm.aes256_en")
set_tests_properties(gcm.aes256_en-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;79;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(gcm.aes128_de-suite "test_suite_gcm.aes128_de")
set_tests_properties(gcm.aes128_de-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;80;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(gcm.aes192_de-suite "test_suite_gcm.aes192_de")
set_tests_properties(gcm.aes192_de-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;81;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(gcm.aes256_de-suite "test_suite_gcm.aes256_de")
set_tests_properties(gcm.aes256_de-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;82;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(gcm.camellia-suite "test_suite_gcm.camellia")
set_tests_properties(gcm.camellia-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;83;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(hmac_drbg.misc-suite "test_suite_hmac_drbg.misc")
set_tests_properties(hmac_drbg.misc-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;84;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(hmac_drbg.no_reseed-suite "test_suite_hmac_drbg.no_reseed")
set_tests_properties(hmac_drbg.no_reseed-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;85;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(hmac_drbg.nopr-suite "test_suite_hmac_drbg.nopr")
set_tests_properties(hmac_drbg.nopr-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;86;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(hmac_drbg.pr-suite "test_suite_hmac_drbg.pr")
set_tests_properties(hmac_drbg.pr-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;87;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(md-suite "test_suite_md")
set_tests_properties(md-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;88;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(mdx-suite "test_suite_mdx")
set_tests_properties(mdx-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;89;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(memory_buffer_alloc-suite "test_suite_memory_buffer_alloc")
set_tests_properties(memory_buffer_alloc-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;90;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(mpi-suite "test_suite_mpi")
set_tests_properties(mpi-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;91;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(pem-suite "test_suite_pem")
set_tests_properties(pem-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;92;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(pkcs1_v15-suite "test_suite_pkcs1_v15")
set_tests_properties(pkcs1_v15-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;93;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(pkcs1_v21-suite "test_suite_pkcs1_v21")
set_tests_properties(pkcs1_v21-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;94;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(pkcs5-suite "test_suite_pkcs5")
set_tests_properties(pkcs5-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;95;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(pk-suite "test_suite_pk")
set_tests_properties(pk-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;96;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(pkparse-suite "test_suite_pkparse")
set_tests_properties(pkparse-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;97;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(pkwrite-suite "test_suite_pkwrite")
set_tests_properties(pkwrite-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;98;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(shax-suite "test_suite_shax")
set_tests_properties(shax-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;99;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(ssl-suite "test_suite_ssl")
set_tests_properties(ssl-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;100;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(timing-suite "test_suite_timing")
set_tests_properties(timing-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;101;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(rsa-suite "test_suite_rsa")
set_tests_properties(rsa-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;102;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(version-suite "test_suite_version")
set_tests_properties(version-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;103;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(xtea-suite "test_suite_xtea")
set_tests_properties(xtea-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;104;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(x509parse-suite "test_suite_x509parse")
set_tests_properties(x509parse-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;105;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
add_test(x509write-suite "test_suite_x509write")
set_tests_properties(x509write-suite PROPERTIES  _BACKTRACE_TRIPLES "/home/jordan/mbedtls/tests/CMakeLists.txt;34;add_test;/home/jordan/mbedtls/tests/CMakeLists.txt;106;add_test_suite;/home/jordan/mbedtls/tests/CMakeLists.txt;0;")
