#!/bin/bash

# Wrap valgrind to run tests from a temp directory. This allows tests to be run in parallel without
# corrupting each other's temp files.

ORIGINAL_ARGS="$@"
TOOL=$(basename $0)
ORIGINAL_VG=$(type -a ${TOOL} | grep -v $PWD | head -n 1 | perl -pe 's/.* //')

pushd . > /dev/null

# cd into temp directory
TMP_VG_DIR=$(mktemp -d /tmp/VG_XXXX)
cd ${TMP_VG_DIR}

# run valgrind from temp directory
${ORIGINAL_VG} ${ORIGINAL_ARGS}
EXITCODE=$?

# cleanup - remove temp directory
popd > /dev/null
rm -rf ${TMP_VG_DIR}
exit ${EXITCODE}
