
node {
    if ( "${env.JOB_NAME}" == 'mbedtls-job-dev' ) {
        echo 'Dispatching release job!'
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'jenkins/release.groovy']]]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '0c890674-8153-4b3e-af1c-d61a6b4ef1d5', url: 'git@github.com:mazimkhan/mbedtls.git']]])
        load 'jenkins/release.groovy'
    }
    dispatch_job()
}

