#!/bin/sh

# Reformat C source files to conform to Mbed TLS coding conventions.

# Copyright The Mbed TLS Contributors
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

list_files () {
  # Ordinary C source files
  set -- '*.h' '*.c' '*.function'
  # Templates from which some C files are generated
  set -- "$@" 'scripts/data_files/*.fmt'
  # Exclude files automatically generated by KreMLin and other
  # everest files contributed as-is.
  set -- "$@" ':!3rdparty/everest/*/[A-Z]*'
  set -- "$@" ':!3rdparty/everest/include/everest/krem*'
  set -- "$@" ':!3rdparty/everest/include/everest/vs*'
  git ls-files "$@"
}

cd "$(git rev-parse --show-toplevel)"
files=$(list_files)

astyle --project=.astylerc $files "$@"
